stages:
  - test
  - build

cargo-test:
  stage: test
  image: rust
  script:
    - rustup component add clippy rustfmt
    - cargo fmt --check
    - cargo clippy -- -D warnings
    - cargo test

cargo-build:
  stage: build
  image: rust
  variables:
    TZWITTER_L1_CONTRACT: "KT1..."
  script:
    - cargo build --release
