[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
# required for the compilation of 09_tzwitter_app
TZWITTER_L1_CONTRACT= "KT1000"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.wasm]
command = "cargo"
args = ["build", "--release","--target", "wasm32-unknown-unknown"]

[tasks.test]
workspace = false
command = "cargo"
args = ["test"]

[tasks.docs-test-clean]
workspace = false
command = "dune"
args = ["clean"]

[tasks.docs-test]
workspace = false
command = "dune"
args = ["runtest"]
dependencies = ["docs-test-clean", "wasm" ]

[tasks.doc]
workspace = false
command = "cargo"
args = ["doc", "--features", "testing", "--no-deps", "--target-dir", "public"]

[tasks.ci]
workspace = false
dependencies = [
    "fmt-check",
    "wasm",
    "docs-test",
    "test"
]
